name: Test Work In Progress

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"

jobs: 
  RunTests:
    name: Test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # packageMode: true # Needs to be enabled when packages are used
          unityVersion: 2022.3.20f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
